# Generated by Django 3.1.5 on 2021-01-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='goals', to='course.Goal'),
        ),
        migrations.AlterField(
            model_name='course',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='course.Job'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='course.Review'),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='course.Skill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teacher.Teacher'),
        ),
    ]
