# Generated by Django 3.1.5 on 2021-01-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210118_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.Course'),
        ),
    ]
