# Generated by Django 3.1.5 on 2021-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210120_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
