# Generated by Django 3.1.5 on 2021-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
