# Generated by Django 3.1.5 on 2021-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_theme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
