# Generated by Django 3.1.5 on 2021-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_subscriber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
