# Generated by Django 3.1.5 on 2021-02-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='price',
            new_name='discount',
        ),
    ]
