# Generated by Django 3.1.5 on 2021-03-05 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20210227_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='promocodes',
            field=models.ManyToManyField(blank=True, related_name='promocodes', to='course.PromoCode'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
