# Generated by Django 3.1.5 on 2021-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads.teacher'),
        ),
    ]
